<a href="https://colab.research.google.com/github/Showcas/NLP/blob/main/04_1_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing with Large Language Models

## 04 - PyTorch

---

In [102]:
!pip3 install torch torchvision torchaudio
!pip install numpy

In [104]:
# With Python version are we running?
import sys

print(sys.version)

3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


## Introduction
[PyTorch](https://pytorch.org/) is a deep learning framework, one of the two main frameworks alongside [TensorFlow](https://www.tensorflow.org/).

Let's start by importing PyTorch. It is called **Py**Torch but it is installed and imported with

`%pip install torch`

In [105]:
import torch

print(torch.__version__)

2.6.0+cu124


In [106]:
# Most Neural Network functions are in the nn submodule:
import torch.nn as nn

In [5]:
# We also use NumPy a lot:
import numpy as np

print(np.__version__)

1.26.4


In [6]:
# Additionally, we import pretty print to print prettily
from pprint import PrettyPrinter

pp = PrettyPrinter().pprint

## Part 1: Tensors

**Tensors** are PyTorch's most basic building block.
Each tensor is a multi-dimensional matrix; for example, a 256x256 square image might be represented by a `3x256x256` tensor, where the first dimension represents color.

Here's how to create a tensor:

In [7]:
list_of_lists = [
    [1, 2],
    [3, 4],
    [5, 6],
]
pp(list_of_lists)

[[1, 2], [3, 4], [5, 6]]


And now in PyTorch:

In [8]:
data = torch.tensor([[0, 1], [2, 3], [4, 5]])
pp(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


Each tenser as a _predefined_ and _fixed_ **data type**:

the major data types you'll handle are floating point numbers in 32bit precision: `torch.float32` and integers `torch.int`.

You can specify this data type during the instatiation explicitly with the `dtype` argument:

In [9]:
data = torch.tensor([[0, 1], [2, 3], [4, 5]], dtype=torch.float32)

pp(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [10]:
pp(data.dtype)

torch.float32


In [11]:
data = torch.tensor([[0.11111111, 1], [2, 3], [4, 5]], dtype=torch.float32)
pp(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [12]:
# A tensor can only have one data type. It uses the highest abstraction for all of them:
data = torch.tensor([[0.11111111, 1], [2, 3], [4, 5]])
pp(data)
pp(data.dtype)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])
torch.float32


Utility functions also exist to create tensors with given shapes and contents:

In [13]:
zeros = torch.zeros(2, 5)  # a tensor of all zeros
pp(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [14]:
ones = torch.ones(3, 4)  # a tensor of all ones
pp(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
rr = torch.arange(1, 10)  # range from [1, 10)
pp(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [16]:
tril = torch.tril(torch.ones(5, 5))

pp(tril)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


Math operators are **broadcasted** and applied elementwise!

In [17]:
pp(rr)

pp(rr + 2)

pp(rr**2)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 1,  4,  9, 16, 25, 36, 49, 64, 81])


This also works with other tensors:

In [18]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])  # shape: (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # shape: (2, 4)

print("A is:")
pp(a)

print("B is:")
pp(b)

A is:
tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [19]:
print("The product is:")
pp(a.matmul(b))

The product is:
tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


In [20]:
print("Special operator specifically for matrix multiplication:")
pp(a @ b)  # +, -, *, @

Special operator specifically for matrix multiplication:
tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


In [21]:
# What about +?

# pp(a + b)

What about the shapes?

In [22]:
v = torch.tensor([1, 2, 3])

pp(v.shape)

torch.Size([3])


In [23]:
m = torch.tensor([[1, 2, 3], [4, 5, 6]])

r = m @ v

print(f"We're multiplying {m.shape} and {v.shape}.")
pp(m)
pp(v)
print(f"The result is {r.shape}.")

pp(r)

We're multiplying torch.Size([2, 3]) and torch.Size([3]).
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
The result is torch.Size([2]).
tensor([14, 32])


The **shape** of a matrix (which can be accessed by `.shape`) is defined as the dimensions of the matrix.

Here's some examples:

In [24]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

pp(matr_2d.shape)
pp(matr_2d)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [25]:
matr_3d = torch.tensor(
    [
        [[1, 2, 3, 4], [-2, 5, 6, 9]],
        [[5, 6, 7, 2], [8, 9, 10, 4]],
        [[-3, 2, 2, 1], [4, 6, 5, 9]],
    ]
)

pp(matr_3d)
pp(matr_3d.shape)

tensor([[[ 1,  2,  3,  4],
         [-2,  5,  6,  9]],

        [[ 5,  6,  7,  2],
         [ 8,  9, 10,  4]],

        [[-3,  2,  2,  1],
         [ 4,  6,  5,  9]]])
torch.Size([3, 2, 4])


**Reshaping** tensors can be used to make batch operations easier (more on that later), but be careful that the data is reshaped in the order you expect:

In [26]:
rr = torch.arange(1, 16)
print(f"The shape is currently {rr.shape}")
print("The contents are currently:")

pp(rr)

The shape is currently torch.Size([15])
The contents are currently:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


In [27]:
rr = rr.view(5, 3)

print(f"The shape is currently {rr.shape}")
print("The contents are currently:")

pp(rr)

The shape is currently torch.Size([5, 3])
The contents are currently:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


Finally, you can also inter-convert tensors with **NumPy arrays**:

In [28]:
# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)
print("This is a torch.tensor:")
pp((data, type(data)))

# torch.Tensor --> numpy.ndarray:
new_arr = data.numpy()
print("This is a np.ndarray:")
pp((new_arr, type(new_arr)))

This is a torch.tensor:
(tensor([[1, 0, 5]]), <class 'torch.Tensor'>)
This is a np.ndarray:
(array([[1, 0, 5]]), <class 'numpy.ndarray'>)


One of the reasons why we use **tensors** is *vectorized operations*:
operations that be conducted in parallel over a particular dimension of a tensor.

In [29]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)

print("Data is:")
pp(data)

Data is:
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])


In [30]:
# We can perform operations like *sum* over each row...
print("Taking the sum over columns:")
pp(data.sum(dim=0))

Taking the sum over columns:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])


In [31]:
# or over each column.
print("Taking thep sum over rows:")
pp(data.sum(dim=1))

Taking thep sum over rows:
tensor([ 28.,  77., 126., 175., 224.])


In [32]:
# Other operations are available:
print("Taking the stdev over rows:")
pp(data.std(dim=1))

Taking the stdev over rows:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [33]:
# No dimension: Sum everything
pp(data.sum())

tensor(630.)


#### TASK 4.1

Write code that creates a `torch.tensor` with the following contents:
$\begin{bmatrix} 2 & 2.3 & -9.6 \\ -1 & -7.2 & 6.3 \end{bmatrix}$

Now compute the average of each row (`.mean()`) and each column.

What's the shape of the results?



In [41]:
### IMPLEMENT YOUR SOLUTION HERE ###

task4_1 = torch.tensor([[2, 2.3, -9.6], [-1, -7.2, 6.3]])

row_mean = task4_1.mean(dim=1)
col_mean = task4_1.mean(dim=0)

print(f"Row: {row_mean.shape}, Column: {col_mean.shape}")

Row: torch.Size([2]), Column: torch.Size([3])


**Indexing**

You can access arbitrary elements of a tensor using the `[]` operator. (Like with ordinary lists, np.arrays, etc.)

In [39]:
# Initialize an example tensor
x = torch.Tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
pp(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [40]:
x.shape

torch.Size([3, 2, 2])

In [42]:
# Access the 0th element, which is the first row
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [43]:
# Which is equivalent to
x[0, :]  # select the row at position 0 and everything else

tensor([[1., 2.],
        [3., 4.]])

In [44]:
x[1,:]

tensor([[5., 6.],
        [7., 8.]])

In [45]:
x[:,1,1]

tensor([ 4.,  8., 12.])

In [46]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [47]:
x[:, 1]

tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])

In [48]:
matr = torch.arange(1, 16).view(5, 3)
pp(matr)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [49]:
matr[0]

tensor([1, 2, 3])

In [50]:
matr[0, :]

tensor([1, 2, 3])

In [51]:
matr[:, 0]

tensor([ 1,  4,  7, 10, 13])

In [52]:
matr[0:3]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
matr[:, 0:2]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]])

In [54]:
matr[0:3, 0:2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [56]:
matr[0][2]

tensor(3)

In [55]:
pp(matr[0:3, 2])
# this is not equal to:
pp(matr[0:3][2])

tensor([3, 6, 9])
tensor([7, 8, 9])


In [57]:
matr[0:3]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
matr[[0, 2, 4]]

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])

We can also index into multiple dimensions with `:`.

In [59]:
# Get the top left element of each element in our tensor
x[:, 0, 0]

tensor([1., 5., 9.])

In [60]:
x[:, :, :]

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [61]:
# Print x again to see our tensor
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [62]:
# Let's access the 0th and 1st elements, each twice
i = torch.tensor([0, 0, 1, 1])
x[i]

# this can be seen as: [x[0], x[0], x[1], x[1]]

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[5., 6.],
         [7., 8.]]])

In [63]:
# Let's access the 0th elements of the 1st and 2nd elements
i = torch.tensor([1, 2])
j = torch.tensor([0])

x[i, j]

tensor([[ 5.,  6.],
        [ 9., 10.]])

We can get a `Python` scalar value from a tensor with `item()`.



In [64]:
# tensor:
pp(x[0, 0, 0])
# scalar:
pp(x[0, 0, 0].item())

tensor(1.)
1.0


#### TASK 4.2

Write a function that returns the 2 diagonals of the matrix `x`.

$$ x = \left( \begin{matrix} [[1 & 2] [3 & 4]] \\ [[5 & 6] [7 & 8]] \\ [[9 & 10] [11 & 12]] \end{matrix} \right) $$

We define the diagonals as follows:

diagonal 1 = [1.0, 6.0, 11.0]
$$ x = \left( \begin{matrix} [[\boxed{\textcolor{red}{1}} & 2] [3 & 4]] \\ [[5 & \boxed{\textcolor{red}{6}}] [7 & 8]] \\ [[9 & 10] [\boxed{\textcolor{red}{11}} & 12]] \end{matrix} \right) $$

diagonal 2 = [2.0, 7.0, 12.0]
$$ x = \left( \begin{matrix} [[1 & \boxed{\textcolor{red}{2}}] [3 & 4]] \\ [[5 & 6] [\boxed{\textcolor{red}{7}} & 8]] \\ [[9 & 10] [11 & \boxed{\textcolor{red}{12}}]] \end{matrix} \right) $$

The function should work with every matrix with the dimensions 3 x 2 x 2.  

In [95]:
def get_diagonal(number, matr):
    """calculate the diagonal of a matrix.

    number -> int: the number of the digaonal to be calculated. example: 0 -> first diagonal

    matr -> torch.Tensor: the matrix to calculate the diagonal of.

    example:
    matr = torch.Tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

    get_diagonal(number=0, matr) -> [1, 6, 11]
    get_diagonal(number=1, matr) -> [2, 7, 12]
    """
    result = []
    ### IMPLEMENT YOUR SOLUTION HERE ###
    shape = matr.shape
    row_numbers = shape[0]
    column_numbers = shape[1]*shape[2]
    for i in range(min (row_numbers, column_numbers)):
      result.append(matr[i].flatten()[number].item())
      number += 1
    return result

In [96]:
test_x = torch.Tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
# first diagonal
pp(get_diagonal(0, test_x))
# expected output: [1.0, 6.0, 11.0]

# second diagonal
pp(get_diagonal(1, test_x))
# expected output: [2.0, 7.0, 12.0]

[1.0, 6.0, 11.0]
[2.0, 7.0, 12.0]


In [97]:
# generate a random 3x2x2 matrix with integers between 0 and 10
rand_x = torch.randint(0, 10, (3, 2, 2))

pp(rand_x)

# first diagonal
pp(get_diagonal(0, rand_x))

# second diagonal
pp(get_diagonal(1, rand_x))


tensor([[[1, 4],
         [3, 4]],

        [[3, 2],
         [7, 6]],

        [[7, 9],
         [4, 2]]])
[1, 2, 4]
[4, 7, 2]


## Autograd
Pytorch is well-known for its automatic differentiation feature.

We can call the `backward()` method to ask `PyTorch` to calculate the gradients, which are then stored in the `grad` attribute.

In [98]:
# Create an example tensor
x = torch.tensor(
    [2.0], requires_grad=True
)  # requires_grad parameter tells PyTorch to store gradients

# Print the gradient if it is calculated
# Currently None since x is a scalar
pp(x.grad)

None


In [99]:
# Calculating the gradient of y with respect to x
y = 3 * x**2

y.backward()

pp(x.grad)  # d(y)/d(x) = d(3x^2)/d(x) = 6x = 12

tensor([12.])


Let's run backprop from a different tensor again to see what happens.

In [101]:
z = 3 * x**2

z.backward()

pp(x.grad)

tensor([36.])


We can see that the `x.grad` is updated to be the sum of the gradients calculated so far.
When we run backprop in a neural network, we sum up all the gradients for a particular neuron before making an update.

This is exactly what is happening here!
This is also the reason why we need to run `zero_grad()` in every training iteration (more on this later).

Otherwise our gradients would keep building up from one training iteration to the other, which would cause our updates to be wrong.

## Neural Network Module

So far we have looked into the tensors, their properties and basic operations on tensors.

These are especially useful to get familiar with if we are building the layers of our network from scratch.
We will use predefined blocks in the `torch.nn` module of `PyTorch`.
We will then put together these blocks to create complex networks.

### **Linear Layer**

We can use `nn.Linear(H_in, H_out)` to create a a linear layer.

This will take a matrix of `(N, *, H_in)` dimensions and output a matrix of `(N, *, H_out)`.
The `*` denotes that there could be arbitrary number of dimensions in between.
The linear layer performs the operation `Ax+b`, where `A` and `b` are initialized randomly.

If we don't want the linear layer to learn the bias parameters, we could initialize our layer with `bias=False`.

In [107]:
# Create the inputs
x = torch.ones(2, 3, 4)
# N * H_in -> N * H_out


# Make a linear layers transforming N,*,H_in dimensinal inputs to N,*,H_out
# dimensional outputs
linear = nn.Linear(4, 2)
linear_output = linear(x)
linear_output

tensor([[[0.8901, 1.0328],
         [0.8901, 1.0328],
         [0.8901, 1.0328]],

        [[0.8901, 1.0328],
         [0.8901, 1.0328],
         [0.8901, 1.0328]]], grad_fn=<ViewBackward0>)

In [108]:
pp(list(linear.parameters()))  # Ax + b

[Parameter containing:
tensor([[ 0.2090,  0.3403,  0.3721, -0.1887],
        [ 0.4327,  0.3635,  0.0590,  0.1296]], requires_grad=True),
 Parameter containing:
tensor([0.1574, 0.0480], requires_grad=True)]


### **Other Module Layers**

There are several other preconfigured layers in the `nn` module.
Some commonly used examples are `nn.Conv2d`, `nn.ConvTranspose2d`, `nn.BatchNorm1d`, `nn.BatchNorm2d`, `nn.Upsample` and `nn.MaxPool2d` among many others.

We will learn more about these as we progress in the course.

For now, the only important thing to remember is that we can treat each of these layers as plug and play components:
we will be providing the required dimensions and `PyTorch` will take care of setting them up.

### **Activation Function Layer**

We can also use the `nn` module to apply activations functions to our tensors.

Activation functions are used to add non-linearity to our network.
Some examples of activations functions are `nn.ReLU()`, `nn.Sigmoid()` and `nn.LeakyReLU()`.

Activation functions operate on each element seperately, so the shape of the tensors we get as an output are the same as the ones we pass in.

In [109]:
pp(linear_output)

tensor([[[0.8901, 1.0328],
         [0.8901, 1.0328],
         [0.8901, 1.0328]],

        [[0.8901, 1.0328],
         [0.8901, 1.0328],
         [0.8901, 1.0328]]], grad_fn=<ViewBackward0>)


In [110]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.7089, 0.7375],
         [0.7089, 0.7375],
         [0.7089, 0.7375]],

        [[0.7089, 0.7375],
         [0.7089, 0.7375],
         [0.7089, 0.7375]]], grad_fn=<SigmoidBackward0>)

### **Putting the Layers Together**
So far we have seen that we can create layers and pass the output of one as the input of the next.

Instead of creating intermediate tensors and passing them around, we can use `nn.Sequentual`, which does exactly that.

In [111]:
block = nn.Sequential(nn.Linear(4, 2), nn.Sigmoid())

x = torch.ones(2, 3, 4)
output = block(x)
pp(output)

tensor([[[0.5966, 0.4689],
         [0.5966, 0.4689],
         [0.5966, 0.4689]],

        [[0.5966, 0.4689],
         [0.5966, 0.4689],
         [0.5966, 0.4689]]], grad_fn=<SigmoidBackward0>)


### Custom Modules

Instead of using the predefined modules, we can also build our own by extending the `nn.Module` class. For example, we can build a the `nn.Linear` (which also extends `nn.Module`) on our own using the tensor introduced earlier! We can also build new, more complex modules, such as a custom neural network. You will be practicing these in the later assignment.

To create a custom module, the first thing we have to do is to extend the `nn.Module`. We can then initialize our parameters in the `__init__` function, starting with a call to the `__init__` function of the super class. All the class attributes we define which are `nn` module objects are treated as parameters, which can be learned during the training. Tensors are not parameters, but they can be turned into parameters if they are wrapped in `nn.Parameter` class.

All classes extending `nn.Module` are also expected to implement a `forward(x)` function, where `x` is a tensor. This is the function that is called when a parameter is passed to our module, such as in `model(x)`.

In [112]:
class MultilayerPerceptron(nn.Module):
    def __init__(self, input_size, hidden_size):
        # Call to the __init__ function of the super class
        super().__init__()

        # Bookkeeping: Saving the initialization parameters
        self.input_size = input_size
        self.hidden_size = hidden_size

        # Defining of our model
        # There isn't anything specific about the naming of `self.model`.
        # It could be something arbitrary.
        self.model = nn.Sequential(
            nn.Linear(self.input_size, self.hidden_size),
            nn.ReLU(),
            nn.Linear(self.hidden_size, self.input_size),
            nn.Sigmoid(),
        )

    def forward(self, x):
        output = self.model(x)
        return output

Here is an alternative way to define the same class.
You can see that we can replace `nn.Sequential` by defining the individual layers in the `__init__` method and connecting the in the `forward` method.

In [113]:
class MultilayerPerceptron(nn.Module):
    def __init__(self, input_size, hidden_size):
        # Call to the __init__ function of the super class
        super().__init__()

        # Bookkeeping: Saving the initialization parameters
        self.input_size = input_size
        self.hidden_size = hidden_size

        # Defining of our layers
        self.linear = nn.Linear(self.input_size, self.hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(self.hidden_size, self.input_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        linear = self.linear(x)
        relu = self.relu(linear)
        linear2 = self.linear2(relu)
        output = self.sigmoid(linear2)
        # compact:
        # output = self.sigmoid(self.linear2(self.relu(self.linear(x))))
        return output

In [114]:
# Make a sample input
x = torch.randn(2, 5)

# Create our model
model = MultilayerPerceptron(5, 3)

# Pass our input through our model
output = model(x)

pp(output)

tensor([[0.4335, 0.5025, 0.4582, 0.5664, 0.4227],
        [0.4446, 0.4433, 0.5242, 0.6306, 0.3950]], grad_fn=<SigmoidBackward0>)


We can inspect the parameters of our model with `named_parameters()` and `parameters()` methods.

In [115]:
pp(list(model.named_parameters()))

[('linear.weight',
  Parameter containing:
tensor([[ 0.4291, -0.4050,  0.1155, -0.1925,  0.4078],
        [ 0.1819,  0.1949, -0.3128, -0.3123,  0.3003],
        [-0.1907, -0.2448, -0.2171,  0.0162, -0.4089]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
tensor([-0.0553, -0.3988,  0.0129], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
tensor([[-0.2886, -0.5697,  0.4033],
        [-0.2338,  0.4246, -0.5181],
        [ 0.4509, -0.1917, -0.3275],
        [ 0.5270, -0.0896, -0.5480],
        [ 0.0054,  0.3788,  0.0511]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
tensor([ 0.0120, -0.0375, -0.2698,  0.1062, -0.4308], requires_grad=True))]


## Optimization
We have showed how gradients are calculated with the `backward()` function.
Having the gradients isn't enought for our models to learn. We also need to know how to update the parameters of our models.

This is where the optomizers comes in.

The `torch.optim` module contains several optimizers that we can use.
Some popular examples are `optim.SGD` and `optim.Adam`.
When initializing optimizers, we pass our model parameters, which can be accessed with `model.parameters()`, telling the optimizers which values it will be optimizing.
Optimizers also has a learning rate (`lr`) parameter, which determines how big of an update will be made in every step.
Different optimizers have different hyperparameters as well.

In [116]:
import torch.optim as optim

In [117]:
# Create the y data
y = torch.ones(10, 5)

# Add some noise to our goal y to generate our x
# We want out model to predict our original data, albeit the noise
x = y + torch.randn_like(y)

pp(x)

tensor([[ 1.0745, -1.6218,  0.9532,  1.2623,  1.0751],
        [ 1.4113,  2.8010, -0.1784,  2.2154,  3.1205],
        [-0.7991,  2.0065,  0.6225,  0.4695,  1.4564],
        [ 2.1085,  0.6262,  1.4878, -0.1812,  2.0440],
        [ 2.2360,  2.2237,  1.6013,  2.7480,  0.9801],
        [ 1.5268,  1.7110,  0.5855, -0.1945,  0.1813],
        [ 1.5312,  1.1611,  0.5125,  1.3977,  0.7255],
        [-0.7598, -1.1114,  1.6302,  0.5251, -0.0785],
        [ 0.4672,  1.5111,  1.5424,  0.8597, -0.0880],
        [ 0.0367, -0.0032,  1.6927,  1.1273,  1.2063]])


Now, we can define our model, optimizer and the loss function.

In [118]:
# Instantiate the model
model = MultilayerPerceptron(5, 3)

# Define the optimizer
adam = optim.Adam(model.parameters(), lr=1e-1)

# Define loss using a predefined loss function
loss_function = nn.BCELoss()

# Calculate how our model is doing now
y_pred = model(x)

loss_function(y_pred, y).item()

0.5326056480407715

In [119]:
# Set the number of epoch, which determines the number of training iterations
n_epoch = 12

for epoch in range(n_epoch):
    # Set the gradients to 0
    adam.zero_grad()

    # Get the model predictions
    y_pred = model(x)

    # Get the loss
    loss = loss_function(y_pred, y)

    # Print stats
    print(f"Epoch {epoch}: traing loss: {loss}")

    # Compute the gradients
    loss.backward()

    # Take a step to optimize the weights
    adam.step()

Epoch 0: traing loss: 0.5326056480407715
Epoch 1: traing loss: 0.3485972583293915
Epoch 2: traing loss: 0.18927600979804993
Epoch 3: traing loss: 0.09003650397062302
Epoch 4: traing loss: 0.04288630932569504
Epoch 5: traing loss: 0.022251568734645844
Epoch 6: traing loss: 0.01242056954652071
Epoch 7: traing loss: 0.0067739482037723064
Epoch 8: traing loss: 0.0036558627616614103
Epoch 9: traing loss: 0.0019736397080123425
Epoch 10: traing loss: 0.0010761512676253915
Epoch 11: traing loss: 0.0005975395324639976


In [120]:
list(model.parameters())

[Parameter containing:
 tensor([[0.5926, 0.7351, 1.1083, 1.2720, 0.5540],
         [1.0356, 0.6725, 0.5352, 1.1505, 1.2361],
         [0.9537, 0.2923, 1.2073, 0.6560, 0.7849]], requires_grad=True),
 Parameter containing:
 tensor([1.0161, 0.5904, 1.1398], requires_grad=True),
 Parameter containing:
 tensor([[0.7327, 0.8069, 0.9246],
         [1.2721, 1.2374, 0.4825],
         [0.9356, 1.3403, 1.0756],
         [0.7621, 1.0769, 1.2029],
         [1.2267, 1.2137, 1.4025]], requires_grad=True),
 Parameter containing:
 tensor([0.9173, 1.0857, 0.5796, 1.0926, 0.7618], requires_grad=True)]

You can see that our loss is decreasing. Let's check the predictions of our model now and see if they are close to our original `y`, which was all `1s`.

In [121]:
# See how our model performs on the training data
y_pred = model(x)
y_pred

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9935, 0.9960, 0.9967, 0.9976, 0.9993],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], grad_fn=<SigmoidBackward0>)

In [122]:
# Create test data and check how our model performs on it
x2 = y + torch.randn_like(y)
y_pred = model(x2)
y_pred

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9998, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], grad_fn=<SigmoidBackward0>)

## Demo: Word Window Classification

Until this part of the notebook, we have learned the fundamentals of PyTorch and built a basic network solving a toy task. Now we will attempt to solve an example NLP task. Here are the things we will learn:

1. Data: Creating a Dataset of Batched Tensors
2. Modeling
3. Training
4. Prediction

In this section, our goal will be to train a model that will find the words in a sentence corresponding to a `LOCATION`, which will be always of span `1` (meaning that `San Fransisco` won't be recognized as a `LOCATION`). Our task is called `Word Window Classification` for a reason. Instead of letting our model to only take a look at one word in each forward pass, we would like it to be able to consider the context of the word in question. That is, for each word, we want our model to be aware of the surrounding words. Let's dive in!

### Data

The very first task of any machine learning project is to set up our training set. Usually, there will be a training corpus we will be utilizing. In NLP tasks, the corpus would generally be a `.txt` or `.csv` file where each row corresponds to a sentence or a tabular datapoint. In our toy task, we will assume that we have already read our data and the corresponding labels into a `Python` list.

In [123]:
# Our raw data, which consists of sentences
corpus = [
    "We always come to Paris",
    "The professor is from Australia",
    "I live in Stanford",
    "He comes from Taiwan",
    "The capital of Turkey is Ankara",
]

#### Preprocessing

To make it easier for our models to learn, we usually apply a few preprocessing steps to our data. This is especially important when dealing with text data. Here are some examples of text preprocessing:
* **Tokenization**: Tokenizing the sentences into words.
* **Lowercasing**: Changing all the letters to be lowercase.
* **Noise removal:** Removing special characters (such as punctuations).
* **Stop words removal**: Removing commonly used words.

Which preprocessing steps are necessary is determined by the task at hand. For example, although it is useful to remove special characters in some tasks, for others they may be important (for example, if we are dealing with multiple languages). For our task, we will lowercase our words and tokenize.


In [124]:
# The preprocessing function we will use to generate our training examples
# Our function is a simple one, we lowercase the letters
# and then tokenize the words.
def preprocess_sentence(sentence):
    return sentence.lower().split()


# Create our training set
train_sentences = [preprocess_sentence(sent) for sent in corpus]
train_sentences

[['we', 'always', 'come', 'to', 'paris'],
 ['the', 'professor', 'is', 'from', 'australia'],
 ['i', 'live', 'in', 'stanford'],
 ['he', 'comes', 'from', 'taiwan'],
 ['the', 'capital', 'of', 'turkey', 'is', 'ankara']]

For each training example we have, we should also have a corresponding label. Recall that the goal of our model was to determine which words correspond to a `LOCATION`. That is, we want our model to output `0` for all the words that are not `LOCATION`s and `1` for the ones that are `LOCATION`s.

In [125]:
# Set of locations that appear in our corpus
locations = set(["australia", "ankara", "paris", "stanford", "taiwan", "turkey"])

# Our train labels
train_labels = [
    [1 if word in locations else 0 for word in sent] for sent in train_sentences
]
train_labels

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1, 0, 1]]

#### Converting Words to Embeddings

Let's look at our training data a little more closely. Each datapoint we have is a sequence of words. On the other hand, we know that machine learning models work with numbers in vectors. How are we going to turn words into numbers? You may be thinking embeddings and you are right!

Imagine that we have an embedding lookup table `E`, where each row corresponds to an embedding. That is, each word in our vocabulary would have a corresponding embedding row `i` in this table. Whenever we want to find an embedding for a word, we will follow these steps:
1. Find the corresponding index `i` of the word in the embedding table: `word → index`.
2. Index into the embedding table and get the embedding: `index → embedding`.

Let's look at the first step. We should assign all the words in our vocabulary to a corresponding index. We can do it as follows:
1. Find all the unique words in our corpus.
2. Assign an index to each.

In [126]:
# Find all the unique words in our corpus
vocabulary = set(w for s in train_sentences for w in s)
pp(vocabulary)

{'always',
 'ankara',
 'australia',
 'capital',
 'come',
 'comes',
 'from',
 'he',
 'i',
 'in',
 'is',
 'live',
 'of',
 'paris',
 'professor',
 'stanford',
 'taiwan',
 'the',
 'to',
 'turkey',
 'we'}


`vocabulary` now contains all the words in our corpus. On the other hand, during the test time, we can see words that are not contained in our vocabulary. If we can figure out a way to represent the unknown words, our model can still reason about whether they are a `LOCATION` or not, since we are also looking at the neighboring words for each prediction.

We introduce a special token, `<unk>`, to tackle the words that are out of vocabulary. We could pick another string for our unknown token if we wanted. The only requirement here is that our token should be unique: we should only be using this token for unknown words. We will also add this special token to our vocabulary.

In [127]:
# Add the unknown token to our vocabulary
vocabulary.add("<unk>")

Earlier we mentioned that our task was called `Word Window Classification` because our model is looking at the surroundings words in addition to the given word when it needs to make a prediction.

For example, let's take the sentence "We always come to Paris". The corresponding training label for this sentence is `0, 0, 0, 0, 1` since only Paris, the last word, is a `LOCATION`. In one pass (meaning a call to `forward()`), our model will try to generate the correct label for one word. Let's say our model is trying to generate the correct label `1` for `Paris`. If we only allow our model to see `Paris`, but nothing else, we will miss out on the important information that the word `to` often times appears with `LOCATION`s.

Word windows allow our model to consider the surrounding `+N` or `-N` words of each word when making a prediction. In our earlier example for `Paris`, if we have a window size of 1, that means our model will look at the words that come immediately before and after `Paris`, which are `to`, and, well, nothing. Now, this raises another issue. `Paris` is at the end of our sentence, so there isn't another word following it. Remember that we define the input dimensions of our `PyTorch` models when we are initializing them. If we set the window size to be `1`, it means that our model will be accepting `3` words in every pass. We cannot have our model expect `2` words from time to time.

The solution is to introduce a special token, such as `<pad>`, that will be added to our sentences to make sure that every word has a valid window around them. Similar to `<unk>` token, we could pick another string for our pad token if we wanted, as long as we make sure it is used for a unique purpose.

In [128]:
# Add the <pad> token to our vocabulary
vocabulary.add("<pad>")


# Function that pads the given sentence
# We are introducing this function here as an example
# We will be utilizing it later in the tutorial
def pad_window(sentence, window_size, pad_token="<pad>"):
    window = [pad_token] * window_size
    return window + sentence + window


# Show padding example
window_size = 2
pad_window(train_sentences[0], window_size=window_size)

['<pad>', '<pad>', 'we', 'always', 'come', 'to', 'paris', '<pad>', '<pad>']

We are just converting our vocabularly to a list to be able to index into it. Sorting is not necessary, we sort to show an ordered `word_to_ind` dictionary. That being said, we will see that having the index for the padding token be `0` is convenient as some PyTorch functions use it as a default value such as `nn.utils.rnn.pad_sequence`, which we will cover in a bit.

In [129]:

ix_to_word = sorted(list(vocabulary))

# Creating a dictionary to find the index of a given word
word_to_ix = {word: ind for ind, word in enumerate(ix_to_word)}
word_to_ix

{'<pad>': 0,
 '<unk>': 1,
 'always': 2,
 'ankara': 3,
 'australia': 4,
 'capital': 5,
 'come': 6,
 'comes': 7,
 'from': 8,
 'he': 9,
 'i': 10,
 'in': 11,
 'is': 12,
 'live': 13,
 'of': 14,
 'paris': 15,
 'professor': 16,
 'stanford': 17,
 'taiwan': 18,
 'the': 19,
 'to': 20,
 'turkey': 21,
 'we': 22}

In [ ]:
ix_to_word[1]

In [130]:
# Given a sentence of tokens, return the corresponding indices
def convert_token_to_indices(sentence, word_to_ix):
    indices = []
    for token in sentence:
        # Check if the token is in our vocabularly. If it is, get it's index.
        # If not, get the index for the unknown token.
        if token in word_to_ix:
            index = word_to_ix[token]
        else:
            index = word_to_ix["<unk>"]
        indices.append(index)
    return indices


# More compact version of the same function
def _convert_token_to_indices(sentence, word_to_ix):
    return [word_to_ix.get(token, word_to_ix["<unk>"]) for token in sentence]


# Show an example
example_sentence = ["we", "always", "come", "to", "kuwait"]
example_indices = convert_token_to_indices(example_sentence, word_to_ix)

restored_example = [ix_to_word[ind] for ind in example_indices]

print(f"Original sentence is: {example_sentence}")
print(f"Going from words to indices: {example_indices}")
print(f"Going from indices to words: {restored_example}")

Original sentence is: ['we', 'always', 'come', 'to', 'kuwait']
Going from words to indices: [22, 2, 6, 20, 1]
Going from indices to words: ['we', 'always', 'come', 'to', '<unk>']


In the example above, `kuwait` shows up as `<unk>`, because it is not included in our vocabulary. Let's convert our `train_sentences` to `example_padded_indices`.

In [131]:
# Converting our sentences to indices
example_padded_indices = [
    convert_token_to_indices(s, word_to_ix) for s in train_sentences
]
example_padded_indices

[[22, 2, 6, 20, 15],
 [19, 16, 12, 8, 4],
 [10, 13, 11, 17],
 [9, 7, 8, 18],
 [19, 5, 14, 21, 12, 3]]

Now that we have an index for each word in our vocabularly, we can create an embedding table with `nn.Embedding` class in `PyTorch`. It is called as follows `nn.Embedding(num_words, embedding_dimension)` where `num_words` is the number of words in our vocabulary and the `embedding_dimension` is the dimension of the embeddings we want to have. There is nothing fancy about `nn.Embedding`: it is just a wrapper class around a trainabe `NxE` dimensional tensor, where `N` is the number of words in our vocabulary and `E` is the number of embedding dimensions. This table is initially random, but it will change over time. As we train our network, the gradients will be backpropagated all the way to the embedding layer, and hence our word embeddings would be updated. We will initiliaze the embedding layer we will use for our model in our model, but we are showing an example here.

In [132]:
# Creating an embedding table for our words
embedding_dim = 5
embeds = nn.Embedding(len(vocabulary), embedding_dim)

# Printing the parameters in our embedding table
pp(list(embeds.parameters()))

[Parameter containing:
tensor([[ 4.7058e-01,  1.0110e+00,  1.0123e+00, -1.3245e+00, -1.2623e-01],
        [ 1.1413e+00, -1.6853e-01,  3.1323e-01, -8.9012e-01,  1.7276e+00],
        [-7.9824e-02, -5.9204e-01,  6.3775e-02, -1.3548e+00,  1.7316e+00],
        [ 2.3735e-01, -3.7877e-01, -3.2348e-01,  7.1900e-01,  8.1425e-01],
        [ 2.1194e+00, -8.6269e-01,  1.4807e-01, -1.4128e+00, -3.7843e-01],
        [ 1.0090e+00, -2.1101e+00, -8.2557e-01, -1.0755e+00,  2.6048e-01],
        [-3.8112e-01,  5.5327e-01, -1.7146e-01,  1.2679e+00, -5.2315e-01],
        [ 1.0597e+00, -4.9105e-01,  3.5022e-01,  1.3663e+00, -1.5006e-01],
        [ 8.9391e-01,  9.0524e-01, -4.2841e-01, -3.2387e-01,  8.8614e-01],
        [ 1.3510e+00,  4.1876e-01, -2.3811e+00,  1.5343e+00,  2.3480e+00],
        [-1.3536e+00, -2.2042e+00,  3.5625e-02, -1.3859e+00, -1.0228e+00],
        [ 7.7261e-01, -1.9342e-01,  7.6653e-01, -1.6245e-01,  2.6987e-01],
        [ 5.3413e-01, -1.6935e+00,  1.6594e+00,  2.2373e+00, -7.2908e-02],
  

To get the word embedding for a word in our vocabulary, all we need to do is to create a lookup tensor. The lookup tensor is just a tensor containing the index we want to look up `nn.Embedding` class expects an index tensor that is of type Long Tensor, so we should create our tensor accordingly.

In [133]:
# Get the embedding for the word Paris
index = word_to_ix["paris"]
index_tensor = torch.tensor(index, dtype=torch.long)
paris_embed = embeds(index_tensor)
paris_embed

tensor([-0.3434, -0.2380,  0.7955,  0.0122,  0.2331],
       grad_fn=<EmbeddingBackward0>)

In [134]:
# We can also get multiple embeddings at once
index_paris = word_to_ix["paris"]
index_ankara = word_to_ix["ankara"]
indices = [index_paris, index_ankara]
indices_tensor = torch.tensor(indices, dtype=torch.long)
embeddings = embeds(indices_tensor)
embeddings

tensor([[-0.3434, -0.2380,  0.7955,  0.0122,  0.2331],
        [ 0.2374, -0.3788, -0.3235,  0.7190,  0.8142]],
       grad_fn=<EmbeddingBackward0>)

Usually, we define the embedding layer as part of our model, which you will see in the later sections of our notebook.

#### Batching Sentences

We have learned about batches in class.
Waiting our whole training corpus to be processed before making an update is costly.
On the other hand, updating the parameters after every training example causes the loss to be less stable between updates.
To combat these issues, we instead update our parameters after training on a batch of data.
This allows us to get a better estimate of the gradient of the global loss.
In this section, we will learn how to structure our data into batches using the `torch.util.data.DataLoader` class.

We will be calling the `DataLoader` class as follows:

`DataLoader(data, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)`.

The `batch_size` parameter determines the number of examples per batch.
In every epoch, we will be iterating over all the batches using the `DataLoader`.
The order of batches is deterministic by default, but we can ask `DataLoader` to shuffle the batches by setting the `shuffle` parameter to `True`.
This way we ensure that we don't encounter a bad batch multiple times.

If provided, `DataLoader` passes the batches it prepares to the `collate_fn`.
We can write a custom function to pass to the `collate_fn` parameter in order to print stats about our batch or perform extra processing.
In our case, we will use the `collate_fn` to:

1. Window pad our train sentences.
2. Convert the words in the training examples to indices.
3. Pad the training examples so that all the sentences and labels have the same length.
   Similarly, we also need to pad the labels. This creates an issue because when calculating the loss, we need to know the actual number of words in a given example.
   We will also keep track of this number in the function we pass to the `collate_fn` parameter.


Because our version of the `collate_fn` function will need to access to our `word_to_ix` dictionary (so that it can turn words into indices), we will make use of the `partial` function in `Python`, which passes the parameters we give to the function we pass it.

In [135]:
from torch.utils.data import DataLoader
from functools import partial


def custom_collate_fn(batch, window_size, word_to_ix):
    # Break our batch into the training examples (x) and labels (y)
    # We are turning our x and y into tensors because nn.utils.rnn.pad_sequence
    # method expects tensors. This is also useful since our model will be
    # expecting tensor inputs.
    x, y = zip(*batch)

    # Now we need to window pad our training examples. We have already defined a
    # function to handle window padding. We are including it here again so that
    # everything is in one place.
    def pad_window(sentence, window_size, pad_token="<pad>"):
        window = [pad_token] * window_size
        return window + sentence + window

    # Pad the train examples.
    x = [pad_window(s, window_size=window_size) for s in x]

    # Now we need to turn words in our training examples to indices. We are
    # copying the function defined earlier for the same reason as above.
    def convert_tokens_to_indices(sentence, word_to_ix):
        return [word_to_ix.get(token, word_to_ix["<unk>"]) for token in sentence]

    # Convert the train examples into indices.
    x = [convert_tokens_to_indices(s, word_to_ix) for s in x]

    # We will now pad the examples so that the lengths of all the example in
    # one batch are the same, making it possible to do matrix operations.
    # We set the batch_first parameter to True so that the returned matrix has
    # the batch as the first dimension.
    pad_token_ix = word_to_ix["<pad>"]

    # pad_sequence function expects the input to be a tensor, so we turn x into one
    x = [torch.LongTensor(x_i) for x_i in x]
    x_padded = nn.utils.rnn.pad_sequence(
        x, batch_first=True, padding_value=pad_token_ix
    )

    # We will also pad the labels. Before doing so, we will record the number
    # of labels so that we know how many words existed in each example.
    lengths = [len(label) for label in y]
    lenghts = torch.LongTensor(lengths)

    y = [torch.LongTensor(y_i) for y_i in y]
    y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

    # We are now ready to return our variables. The order we return our variables
    # here will match the order we read them in our training loop.
    return x_padded, y_padded, lenghts

This function seems long, but it really doesn't have to be. Check out the alternative version below where we remove the extra function declarations and comments.

In [136]:
def _custom_collate_fn(batch, window_size, word_to_ix):
    # Prepare the datapoints
    x, y = zip(*batch)
    x = [pad_window(s, window_size=window_size) for s in x]
    x = [convert_tokens_to_indices(s, word_to_ix) for s in x]

    # Pad x so that all the examples in the batch have the same size
    pad_token_ix = word_to_ix["<pad>"]
    x = [torch.LongTensor(x_i) for x_i in x]
    x_padded = nn.utils.rnn.pad_sequence(
        x, batch_first=True, padding_value=pad_token_ix
    )

    # Pad y and record the length
    lengths = [len(label) for label in y]
    lenghts = torch.LongTensor(lengths)
    y = [torch.LongTensor(y_i) for y_i in y]
    y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

    return x_padded, y_padded, lenghts

Now, we can see the `DataLoader` in action.

In [137]:
# Parameters to be passed to the DataLoader
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# Instantiate the DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# Go through one loop
counter = 0
for batched_x, batched_y, batched_lengths in loader:
    print(f"Iteration {counter}")
    print("Batched Input:")
    print(batched_x)
    print("Batched Labels:")
    print(batched_y)
    print("Batched Lengths:")
    print(batched_lengths)
    print("")
    counter += 1

Iteration 0
Batched Input:
tensor([[ 0,  0, 22,  2,  6, 20, 15,  0,  0],
        [ 0,  0, 19, 16, 12,  8,  4,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]])
Batched Lengths:
tensor([5, 5])

Iteration 1
Batched Input:
tensor([[ 0,  0,  9,  7,  8, 18,  0,  0,  0,  0],
        [ 0,  0, 19,  5, 14, 21, 12,  3,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 1]])
Batched Lengths:
tensor([4, 6])

Iteration 2
Batched Input:
tensor([[ 0,  0, 10, 13, 11, 17,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 1]])
Batched Lengths:
tensor([4])



The batched input tensors you see above will be passed into our model. On the other hand, we started off saying that our model will be a window classifier. The way our input tensors are currently formatted, we have all the words in a sentence in one datapoint. When we pass this input to our model, it needs to create the windows for each word, make a prediction as to whether the center word is a `LOCATION` or not for each window, put the predictions together and return.

We could avoid this problem if we formatted our data by breaking it into windows beforehand. In this example, we will instead how our model take care of the formatting.

Given that our `window_size` is `N` we want our model to make a prediction on every `2N+1` tokens. That is, if we have an input with `9` tokens, and a `window_size` of `2`, we want our model to return `5` predictions. This makes sense because before we padded it with `2` tokens on each side, our input also had `5` tokens in it!

We can create these windows by using for loops, but there is a faster `PyTorch` alternative, which is the `unfold(dimension, size, step)` method. We can create the windows we need using this method as follows:

In [138]:
# Print the original tensor
print(f"Original Tensor: ")
print(batched_x)
print("")

# Create the 2 * 2 + 1 chunks
chunk = batched_x.unfold(1, window_size * 2 + 1, 1)
# unfold(1, 5, 1) -> dimension 1, window size 5, step 1
print(f"Windows: ")
print(chunk)

Original Tensor: 
tensor([[ 0,  0, 10, 13, 11, 17,  0,  0]])

Windows: 
tensor([[[ 0,  0, 10, 13, 11],
         [ 0, 10, 13, 11, 17],
         [10, 13, 11, 17,  0],
         [13, 11, 17,  0,  0]]])


### Model

Now that we have prepared our data, we are ready to build our model. We have learned how to write custom `nn.Module` classes. We will do the same here and put everything we have learned so far together.

In [139]:
class WordWindowClassifier(nn.Module):
    def __init__(self, hyperparameters, vocab_size, pad_ix=0):
        super(WordWindowClassifier, self).__init__()

        """ Instance variables """
        self.window_size = hyperparameters["window_size"]
        self.embed_dim = hyperparameters["embed_dim"]
        self.hidden_dim = hyperparameters["hidden_dim"]
        self.freeze_embeddings = hyperparameters["freeze_embeddings"]

        """ Embedding Layer
        Takes in a tensor containing embedding indices, and returns the
        corresponding embeddings. The output is of dim
        (number_of_indices * embedding_dim).

        If freeze_embeddings is True, set the embedding layer parameters to be
        non-trainable. This is useful if we only want the parameters other than the
        embeddings parameters to change.

        """
        self.embeds = nn.Embedding(vocab_size, self.embed_dim, padding_idx=pad_ix)
        if self.freeze_embeddings:
            self.embed_layer.weight.requires_grad = False

        """ Hidden Layer with Tanh Activation
        """
        full_window_size = 2 * window_size + 1
        self.hidden_layer = nn.Sequential(
            nn.Linear(full_window_size * self.embed_dim, self.hidden_dim), nn.Tanh()
        )

        """ Output Layer
        """
        self.output_layer = nn.Linear(self.hidden_dim, 1)

        """ Probabilities
        """
        self.probabilities = nn.Sigmoid()

    def forward(self, inputs):
        """
        Let B:= batch_size
            L:= window-padded sentence length
            D:= self.embed_dim
            S:= self.window_size
            H:= self.hidden_dim

        inputs: a (B, L) tensor of token indices
        """
        B, L = inputs.size()

        """
        Reshaping.
        Takes in a (B, L) LongTensor
        Outputs a (B, L~, S) LongTensor
        """
        # Fist, get our word windows for each word in our input.
        token_windows = inputs.unfold(1, 2 * self.window_size + 1, 1)
        _, adjusted_length, _ = token_windows.size()

        # Good idea to do internal tensor-size sanity checks, at the least in comments!
        assert token_windows.size() == (B, adjusted_length, 2 * self.window_size + 1)

        """
        Embedding.
        Takes in a torch.LongTensor of size (B, L~, S)
        Outputs a (B, L~, S, D) FloatTensor.
        """
        embedded_windows = self.embeds(token_windows)

        """
        Reshaping.
        Takes in a (B, L~, S, D) FloatTensor.
        Resizes it into a (B, L~, S*D) FloatTensor.
        -1 argument "infers" what the last dimension should be based on leftover axes.
        """
        embedded_windows = embedded_windows.view(B, adjusted_length, -1)

        """
        Layer 1.
        Takes in a (B, L~, S*D) FloatTensor.
        Resizes it into a (B, L~, H) FloatTensor
        """
        layer_1 = self.hidden_layer(embedded_windows)

        """
        Layer 2
        Takes in a (B, L~, H) FloatTensor.
        Resizes it into a (B, L~, 1) FloatTensor.
        """
        output = self.output_layer(layer_1)

        """
        Softmax.
        Takes in a (B, L~, 1) FloatTensor of unnormalized class scores.
        Outputs a (B, L~, 1) FloatTensor of (log-)normalized class scores.
        """
        output = self.probabilities(output)
        output = output.view(B, -1)

        return output

### Training

We are now ready to put everything together. Let's start with preparing our data and intializing our model. We can then intialize our optimizer and define our loss function. This time, instead of using one of the predefined loss function as we did before, we will define our own loss function.

In [140]:
from tqdm.auto import trange

In [141]:
# Prepare the data
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# Instantiate a DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# Initialize a model
# It is useful to put all the model hyperparameters in a dictionary
model_hyperparameters = {
    "batch_size": 4,
    "window_size": 2,
    "embed_dim": 25,
    "hidden_dim": 25,
    "freeze_embeddings": False,
}

vocab_size = len(word_to_ix)
model = WordWindowClassifier(model_hyperparameters, vocab_size)

# Define an optimizer
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


# Define a loss function, which computes to binary cross entropy loss
def loss_function(batch_outputs, batch_labels, batch_lengths):
    # Calculate the loss for the whole batch
    bceloss = nn.BCELoss()
    loss = bceloss(batch_outputs, batch_labels.float())

    # Rescale the loss. Remember that we have used lengths to store the
    # number of words in each training example
    loss = loss / batch_lengths.sum().float()

    return loss

Unlike our earlier example, this time instead of passing all of our training data to the model at once in each epoch, we will be utilizing batches. Hence, in each training epoch iteration, we also iterate over the batches.

In [142]:
# Function that will be called in every epoch
def train_epoch(loss_function, optimizer, model, loader):
    # Keep track of the total loss for the batch
    total_loss = 0
    for batch_inputs, batch_labels, batch_lengths in loader:
        # Clear the gradients
        optimizer.zero_grad()
        # Run a forward pass
        outputs = model.forward(batch_inputs)
        # Compute the batch loss
        loss = loss_function(outputs, batch_labels, batch_lengths)
        # Calculate the gradients
        loss.backward()
        # Update the parameteres
        optimizer.step()
        total_loss += loss.item()

    return total_loss


# Function containing our main training loop
def train(loss_function, optimizer, model, loader, num_epochs=10000):
    # Iterate through each epoch and call our train_epoch function
    for epoch in trange(num_epochs):
        epoch_loss = train_epoch(loss_function, optimizer, model, loader)
        if epoch % 100 == 0:
            print(f"Epoch {epoch:>3}: {epoch_loss:.4f}")

Let's start training!

In [143]:
num_epochs = 1005

train(loss_function, optimizer, model, loader, num_epochs=num_epochs)

  0%|          | 0/1005 [00:00<?, ?it/s]

Epoch   0: 0.3314
Epoch 100: 0.2162
Epoch 200: 0.1713
Epoch 300: 0.1308
Epoch 400: 0.0960
Epoch 500: 0.0706
Epoch 600: 0.0535
Epoch 700: 0.0425
Epoch 800: 0.0344
Epoch 900: 0.0314
Epoch 1000: 0.0263


### Prediction

#### TASK 4.3

Write code to prepare the prediction with the example sentence `test_corpus = ["She comes from Paris"]`.

1. **Create the test sentence with preprocessing and labels**:
    - First, preprocess the example sentence by converting it to lowercase and splitting it into words (tokens).
    - Create labels for the sentence. For this example, assume a simple binary label indicating some property of the words in the sentence.
  
2. **Create a test loader**:
    - Create a `DataLoader` to load the test sentence and its corresponding labels.
    - Set the `batch_size` to 1 (as you are testing a single sentence).
    - Set `shuffle` to `False` to preserve the order of the sentence.
    - Use a custom collate function (e.g., `custom_collate_fn`) to process the data during batching. You may also need to define `window_size` and a dictionary `word_to_ix` to map words to indices, depending on your implementation.


We want to run the prediciton using the following code:
```Python
for test_instance, labels, _ in test_loader:
    rew_prediction = model.forward(test_instance)
```

In [160]:
### IMPLEMENT YOUR SOLUTION HERE ###
def preprocess(sentence, word_to_ix):
    unk_index = word_to_ix.get("<UNK>", 0)
    return [word_to_ix.get(word.lower(), unk_index) for word in sentence.split()]


test_corpus = ["She comes from Paris"]
test_labels = [[0, 0, 0, 1]]

test_sentence = [preprocess(test_corpus[0], word_to_ix)]
test_data = list(zip(test_sentence, test_labels))

test_loader = DataLoader(test_data, batch_size=1, shuffle=False, collate_fn=partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix))

for test_instance, labels, _ in test_loader:
    rew_prediction = model.forward(test_instance)


Next we can create our predictions for the test sentence and print the raw predictions from the model.

In [161]:
# show raw predictions for the test data
with torch.no_grad():
    for test_instance, labels, _ in test_loader:
        raw_prediction = model.forward(test_instance)
print(raw_prediction)

# raw_prediction shoul be a tensor of shape (1, 4): for example tensor([[0.0580, 0.0262, 0.2414, 0.9018]])

tensor([[0.3326, 0.4016, 0.2985, 0.2021]])


In jupyter notebooks we can test the inference time of our model using the %%timeit magic command. With this command we run the cell multiple times and calculate the average time it takes to run the cell.

In [162]:
%%timeit
for test_instance, labels, _ in test_loader:
    raw_prediction = model.forward(test_instance)


570 µs ± 68.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Now we compare the time with the no_grad context manager. This context manager allows us to disable gradient computation, which provides a speedup and is useful when we are only interested in inference.

In [163]:
%%timeit
with torch.no_grad():
    for test_instance, labels, _ in test_loader:
        raw_prediction = model.forward(test_instance)


426 µs ± 17.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


With this, we have build a simple word window classifier using PyTorch. You should now have a basic understanding of how to build a simple neural network using PyTorch.